### ISSUE TITLE
Client Main 

### ISSUE THREAD

**Issue by E4sy06** [ScreepCode/TypingGame#1]
Hey Niki ich bins E4sy,
Wir müssen nun auch im LK das gleiche machen wie ihr damals und da hab ich mich direkt an dein Projekt erinnert...
Ich hab deins Ausprobiert, Problem ich kann mich weder Anmelden, nen Acc erstellen, noch als Gast spielen...
Vlt hast du nen Tipp ; )

**Comment by ScreepCode** [comment]
Hey,
Wie bereits vermutet fehlt die Dependancy zum SQLite Driver.
Den kann man je nach dem welche IDE du verwendest, im Classpath hinzufügen.
In eclipse ist es die .classpath Datei, in intellij wiederum eine xxx.iml Datei, wo die JDBC eingebunden wird.

Ich hoffe, das hilft dir weiter
